### ISSUE TITLE
Als gemeentesecretaris en manager van een gemeente, wil ik een helder eindbeeld van het uitontwikkelde stelsel

### ISSUE THREAD

**Issue by jeffreygortmaker1** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#104]
zodat ik een ‘roadmap’ kan ontwikkelen waarin de organisatie van A naar B gaat.

**Comment by markbacker** [comment]
Dit is een kopie van issue #103

**Comment by TCIMEddy** [comment]
@markbacker Dank, ik close hem nu!

**Comment by jgortmaker1** [comment]
heeft een ander doel en is extern aangedragen. ik reopen hem ...
is misschien met de uitwerking van #103 wel al opgelost, maar misschien ook niet...

**Comment by TCIMEddy** [comment]
@jgortmaker1 goede correctie geef ook even prio mee

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als gemeentesecretaris en manager van een gemeente, wil ik een helder eindbeeld van het uitontwikkelde stelsel](https://trello.com/c/XggHq9PA/63-als-gemeentesecretaris-en-manager-van-een-gemeente-wil-ik-een-helder-eindbeeld-van-het-uitontwikkelde-stelsel)
