### ISSUE TITLE
Als informatiespecialist wil ik weten welke api's beschikbaar en bruikbaar zijn

### ISSUE THREAD

**Issue by jeffreygortmaker1** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#105]
zodat ik ze in mijn eigen situatie kan toepassen.

**Comment by TCIMEddy** [comment]
@jgortmaker1 Lijkt me hoge prioriteit en een mooie klus voor @HenriKorver (is wellicht al overzicht van)

**Comment by TCIMEddy** [comment]
➤ Eddy Timmer commented:

@jeffreygortmaker1 Nog steeds hoge prio?

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als informatiespecialist wil ik weten welke api's beschikbaar en bruikbaar zijn](https://trello.com/c/DFp6thyS/62-als-informatiespecialist-wil-ik-weten-welke-apis-beschikbaar-en-bruikbaar-zijn)
