### ISSUE TITLE
Als informatiespecialist wil ik een heldere uitleg van het concept Common Ground

### ISSUE THREAD

**Issue by jeffreygortmaker1** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#107]
zodat ik er in mijn eigen gemeente mee aan de slag kan.

**Comment by TCIMEddy** [comment]
Keurig!!!

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als informatiespecialist wil ik een heldere uitleg van het concept Common Ground](https://trello.com/c/waN06pmS/60-als-informatiespecialist-wil-ik-een-heldere-uitleg-van-het-concept-common-ground)
