### ISSUE TITLE
Als VNG architect wil ik dat alle actuele 'beleids'stukken van SO, CG, +1 en GL centraal beschikbaar zijn ...

### ISSUE THREAD

**Issue by WimBakkeren** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#117]
... zodat ik eenvoudig terug kan vallen op en verwijzen naar de meest recente vastgestelde documenten die van invloed zijn op de informatievoorziening van gemeenten.

Toelichting: Ik heb behoefte aan een centrale plek waar (verwijzingen naar) de actuele, vastgestelde versies van documenten over Samen Organiseren, Common Ground, +1-gemeente, Gegevenslandschap e.d. beschikbaar zijn. Bij voorkeur aangevuld met (verwijzingen naar) andere relevante vastgestelde stukken zoals de Agenda Digitale Overheid.

Dit overzicht van relevante stukken moet beheerd worden.

Nu moet iedereen zelf op zoek naar de laatste versie van relevante stukken met het risico dat je onvolledig bent en niet de laatste versies tot je beschikking hebt. Bovendien kost het steeds tijd om de juiste documenten te vinden.

- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en leesbaar)
- [x] Voorzien van Definition of Done 
- [x] Voorzien van taken (naam, uren, smart)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] Users en stakeholder benoemd
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**

- [ ] Peer review heeft plaatsgevonden
- [ ] Demo-gereed (kan getoond worden tijdens demo en is demo materiaal is gereed)
- [ ] Product Owner en Scrumteam akkoord

**Users**

- Teamleden Squad architectuur
- (Evt.) geïnteresseerden in bewegingen Samen Organiseren, Common Ground, +1-gemeente, Gegevenslandschap, etc.

**Stakeholders**
- Taskforce Samen Organiseren
- Auteurs documentatie Samen Organiseren, Common Ground, +1-gemeente, Gegevenslandschap, etc. (waaronder teamleden)

**Acceptatiecriteria**

- [ ] Duidelijk en leesbaar voor doelgroep (product owner/scrumteam)
- [ ] Scrumteam begrijpt het en ondersteunt het

**Globale oplossingrichting**
- Een bibliotheek met relevante achtergrondinformatie op GEMMA Online

**Taken**
- [ ] Relevante documentatie bijeen vegen
- [ ] Publiceren documentatie op GEMMA Online

**Comment by jgortmaker1** [comment]
lijkt me een belangrijk punt. Enerzijds voor onszelf. Anderzijds ook voor de buitenwereld. (als wij zelf al moeite hebben met het vinden...)

@hdksi kun jij deze ready maken?

**Comment by TCIMEddy** [comment]
@hdksi Is dit nog in progress

**Comment by hdksi** [comment]
Voor intern gebruik hebben we een map in het kanaal 'algemeen' in teams. Iedereen kan daar zelf relevante achtergrondinfo kwijt. Mapje is alleen niet beheerd.
