### ISSUE TITLE
Als productowner architectuur wil ik een afgestemde versie van de principes gegevenslandschap hebben

### ISSUE THREAD

**Issue by jeffreygortmaker1** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#120]
..zodat ik zeker weet dat de opgestelde principes gedragen en begrepen worden..

**Toelichting**
klein voorschotje op review en demo eerste zet principes. Volgens mij goed genoeg om het gesprek met Stakeholders mee aan te gaan om te kijken of deze goed begrepen worden en ze aan te scherpen. Dit voor sprint 2
Dit naast het vervolledigen van de benodigde set principes, zie #119

**Comment by adgerrits** [comment]
Prima om hogere versnelling te pakken; kan er vanaf donderdag aan werken. Belangrijke beslissing is om te bepalen welke soorten principes we onderscheiden. Arnoud beschrijft ze als ' redelijk tactisch/operationeel', ik zou het eerder 'gegevens- en applicaties georienteerd' noemen waar Arnoud meer strategische lange termijn doelen noemt. Beide nuttig en nodig denk ik. Kwam eerder mbt Common Ground ook tot een vergelijkbare conclusie dus dat gaan we daar ook tegenkomen.

**Comment by TCIMEddy** [comment]
➤ Jeffrey Gortmaker commented:

dit is een afgestemde versie van i95. maar i119 is inmiddels gereed, dus deze kan op done (er valt hier ook niets op te reviewen)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als productowner architectuur wil ik een afgestemde versie van de principes gegevenslandschap hebben](https://trello.com/c/2ia4C3KC/47-als-productowner-architectuur-wil-ik-een-afgestemde-versie-van-de-principes-gegevenslandschap-hebben)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als productowner architectuur wil ik een afgestemde versie van de principes gegevenslandschap hebben](https://trello.com/c/2ia4C3KC/47-als-productowner-architectuur-wil-ik-een-afgestemde-versie-van-de-principes-gegevenslandschap-hebben)
