### ISSUE TITLE
Reviewen/beoordelen analyse herbruikbaarheid componenten

### ISSUE THREAD

**Issue by jgortmaker1** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#145]
nog aanvullen. Analyse vanuit casus Haarlem. Doc opvragen bij Wouter B.

Staat op sprintboard 2 toepassingen die voor 31/12 gereed moeten zijn. (Lagenmode HLM en MOR Amsterdam)

**Comment by TCIMEddy** [comment]
@jgortmaker1 User story beter beschrijven en DoD
