### ISSUE TITLE
Als developer wil ik weten wanneer ik Linked data rechtstreeks kan gebruiken en wanneer ik NLX moet toepassen op mijn http requests(incl http rewrite)

### ISSUE THREAD

**Issue by jeffreygortmaker1** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#146]
zodat ik een mijn applicatie architectuur uitwerk in lijn met de Common Ground en NLX visie

Globale oplossingsrichting
Amsterdam wil graag Linked Data gebruiken met/zonder NLX. De URI’s zouden hetzelfde moeten blijven. Dat is momenteel met NLX niet zo (fictief voorbeeld):

https://outway.local/kadaster/api/v1/perceel
vs.
https://kadaster.nl/api/v1/perceel

We kunnen op meerdere manieren mee omgaan:

1. vasthouden aan huidige opzet, is enerzijds correcter qua hoe internet zou moeten werken anderzijds lastig met linked data (lopen we dan ook tegen aan met ZDS2.0)
1. rewriting toepassen: een stukje software die URI’s heen en weer vertaalt. Geen geweldige keuze qua ‘lelijk’
1. http proxy toepassen: het is wellicht mogelijk (onderzoek nodig!) om de gewenste link (URI strategie compatible) rechtstreeks in NLX te gebruiken. Wel vereist dit dan dat de NLX outway als gateway (http proxy) wordt gebruikt voor clients die het aanroepen. Niet helemaal zuiver als het gaat om afhandeling DNS, mogelijk andere nadelen, wel hoog gebruiksgemak.

**Een combi van opties is eventueel ook mogelijk.**

_Deze keuze maken we liever niet alleen, want heeft veel impact op mogelijkheden gegevenslandschap._

NB. dit advies is nodig ikv toepassing MOR Amsterdam die voor 31/12 af moet

**Comment by jgortmaker1** [comment]
aub ready maken (en titel aanpassen)

**Comment by mrtn78** [comment]
Na wat inlezen is mijn eerste beeld: 
Een DNS is als een telefoonboek. een FQDN is een unieke naam die verwijst naar een authentiek (telefoon)nummer. Door rewriting te doen ga je in feite een intern telefoonboek opstellen met interne namen die verwijzen naar unieke namen die op zich weer verwijzen naar authentieke nummers. In de praktijk krijg je dan altijd een combinatie van interne namen en unieke namen wat voor verwarring gaat zorgen. bovendien ben je afhankelijk van 2 boeken om op te vragen wat het nummer is. Deze extra stap en extra afhankelijkheid brengt overhead en complexiteit met zich mee die je juist wilt voorkomen. 

een tweede overweging vanuit certificaat gebruik is dat het certificaat gebonden is aan een fqdn en de relatie kan worden gelegd tussen het de fqdn in het cert. en de fqdn in de uri. dir kan uiteraard niet meer wanneer nlx een rewrite doet.

een derde overweging is dat men direct vanuit de UI een liked data resource aan kan roepen (zeker wanneer dit open data is) een NLX aanroep middels een outway is niet direct vanuit de UI en vergt dus extra resources vanuit de dienstenafnemer die de dienstenaanbieder niet vereist.

**Comment by jgortmaker1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/ZwEh9S1h/1-test)

**Comment by ehotting** [comment]
Hierover is binnen NLX team e.e.a. uitgedacht afgelopen week, waardoor het mogelijk wordt om links transparant door NLX te laten lopen (lijkt op scenario 3). @mrtn78 graag contact met GJ

**Comment by TCIMEddy** [comment]
@jgortmaker1 hmmm nee sorry per ongeluk

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als developer wil ik weten wanneer ik Linked data rechtstreeks kan gebruiken en wanneer ik NLX moet toepassen op mijn http requests(incl http rewrite)](https://trello.com/c/zd5LOMQ5/21-als-developer-wil-ik-weten-wanneer-ik-linked-data-rechtstreeks-kan-gebruiken-en-wanneer-ik-nlx-moet-toepassen-op-mijn-http-reque)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als developer wil ik weten wanneer ik Linked data rechtstreeks kan gebruiken en wanneer ik NLX moet toepassen op mijn http requests(incl http rewrite)](https://trello.com/c/zd5LOMQ5/21-als-developer-wil-ik-weten-wanneer-ik-linked-data-rechtstreeks-kan-gebruiken-en-wanneer-ik-nlx-moet-toepassen-op-mijn-http-reque)
