### ISSUE TITLE
Als product owner wil ik inzicht hebben in de samenhang van de UPL, het verwerkingsregister en zaaktypen

### ISSUE THREAD

**Issue by arnoudquanjer** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#162]
Omschrijving user story
De Uniforme Productnamenlijst (UPL) is een onderdeel van Samenwerkende
Catalogi, de standaard voor uitwisseling van informatie over producten en
diensten van de overheid. De UPLis een middel om met deze diversiteit om te gaan.
De UPL is een lijst waarop namen voor producten en diensten van alle overheden staan. Aan
de autonomie van de betreffende organisaties wordt daarbij niet getornd: deze
mogen zelf bepalen welke producten en diensten zij aanbieden en hoe ze die
noemen en presenteren. Door deze producten en diensten in de productcatalogus
(of op de website) wel te labelen met de eenduidige ‘uniforme productnamen’ is
duidelijk waar het over gaat, en kunnen andere partijen (bijvoorbeeld websites als
het Digitaal Ondernemersplein) burgers en ondernemers de informatie op maat en
gebundeld voorschotelen. Hergebruik van productinformatie wordt daardoor
mogelijk. 

Onderdeel van de UPL zijn een productnaam en een grondslag. Deze elementen komen als 'doel' en 'wettelijke grondslag' ook voor in het verwerkingsregister. Gezien het doel van de UPL lijkt het logisch om de productnamen en grondslagen van de UPL her te gebruiken binnen het verwerkingsregister.

Daarnaast wordt door VNG-R de zaaktypecatalogus (ZTC) beschikbaar gesteld. De ZTC bevat de beschrijving van alle zaaktypen die binnen een organisatie of domein uitgevoerd
worden, en vormt zo de blauwdruk voor de zaakdossiers. Onderzocht dient te worden of er een relatie te leggen valt of is met de UPL en het register van verwerkingen.

_UPL voor gemeenten_
https://standaarden.overheid.nl/owms/oquery/UPL-gemeente.plain

_Voorbeeld verwerkingsregister_
https://www.gemeentewestland.nl/fileadmin/files/Privacy/Openbare_versie_verwerkingsregister_mei_2018_versie0.1.1.pdf

_Zaaktypecatalogus_
https://www.gemmaonline.nl/index.php/GEMMA_Zaaktypecatalogus
**Users**

**Comment by TCIMEddy** [comment]
@jgortmaker1 mooi ingebrachte User Story (zo compleet)... graag prio en/of juiste kolom

**Comment by jgortmaker1** [comment]
de collega's hebben het nodig, dus ik geef er hoge prioriteit aan

**Comment by arnoudquanjer** [comment]
@TCIMEddy, @jgortmaker1, deze user story is wat mij betreft ready.

**Comment by gertjanvanderkooij** [comment]
Hoe verhoudt de nadere uitwerking van dit issue zich tot Gebeurtenissen (Administratieve handelingen), zoals deze door processystemen worden ondersteund? In het bronsysteem als Verantwoordingsgegevens werden opgenomen en via Notificaties in de vorm van zogenaamde triggerberichten aan afnemers worden gemeld. 

Ik ben in die zin net als jullie op zoek naar de betekenis van UPL, Zaaktypen, Verwerkingsregister, Administratieve handelingen cq. Gebeurtenissen in het toekomstig Gegevenslandschap.  

Bijgaand de lijst van Administratieve handelingen die we hanteerden bij Operatie BRP:
[StatusOverzicht_AdministratieveHandelingen_Berichten.pdf](https://github.com/VNG-Realisatie/Squad-Architectuur-Samen-Organiseren/files/2713011/StatusOverzicht_AdministratieveHandelingen_Berichten.pdf)

**Comment by jeffreygortmaker1** [comment]
@gertjanvanderkooij dank voor de vraag/suggestie. Nemen we mee.

**Comment by gertjanvanderkooij** [comment]
@jeffreygortmaker1 OK; als er nog aanvullende vragen zijn, contacten we even!

**Comment by sergei-maertens** [comment]
Vandaag heb ik in onze mock-component een Product/Dienst resource toegevoegd om hiernaar te kunnen refereren vanuit het ZTC: https://github.com/VNG-Realisatie/gemma-mock-overigeregistratiecomponenten/commit/d22ac0d50b707bd77ec671e9cfb44b1a2f3e9017

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als product owner wil ik inzicht hebben in de samenhang van de UPL, het verwerkingsregister en zaaktypen](https://trello.com/c/NWCUVBnp/5-als-product-owner-wil-ik-inzicht-hebben-in-de-samenhang-van-de-upl-het-verwerkingsregister-en-zaaktypen)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als product owner wil ik inzicht hebben in de samenhang van de UPL, het verwerkingsregister en zaaktypen](https://trello.com/c/NWCUVBnp/5-als-product-owner-wil-ik-inzicht-hebben-in-de-samenhang-van-de-upl-het-verwerkingsregister-en-zaaktypen)

**Comment by gertjanvanderkooij** [comment]
Vraagje:
Waarom is mijn opmerking incl. bestand met specifieke Burgerzaken-handelingen verwijderd? Nog wel ergens bewaard gebleven?

**Comment by TCIMEddy** [comment]
Hoe verhoudt de nadere uitwerking van dit issue zich tot Gebeurtenissen (Administratieve handelingen), zoals deze door processystemen worden ondersteund? In het bronsysteem als Verantwoordingsgegevens werden opgenomen en via Notificaties in de vorm van zogenaamde triggerberichten aan afnemers worden gemeld.

Ik ben in die zin net als jullie op zoek naar de betekenis van UPL, Zaaktypen, Verwerkingsregister, Administratieve handelingen cq. Gebeurtenissen in het toekomstig Gegevenslandschap.

Bijgaand de lijst van Administratieve handelingen die we hanteerden bij Operatie BRP:
StatusOverzicht_AdministratieveHandelingen_Berichten.pdf

**Comment by TCIMEddy** [comment]
Hebben we opgepakt in het issues en is zeker niet weg hoor. Maar dank voor attenderen en ik zal er op letten.

**Comment by gertjanvanderkooij** [comment]
> 
> 
> Hoe verhoudt de nadere uitwerking van dit issue zich tot Gebeurtenissen (Administratieve handelingen), zoals deze door processystemen worden ondersteund? In het bronsysteem als Verantwoordingsgegevens werden opgenomen en via Notificaties in de vorm van zogenaamde triggerberichten aan afnemers worden gemeld.
> 
> Ik ben in die zin net als jullie op zoek naar de betekenis van UPL, Zaaktypen, Verwerkingsregister, Administratieve handelingen cq. Gebeurtenissen in het toekomstig Gegevenslandschap.
> 
> Bijgaand de lijst van Administratieve handelingen die we hanteerden bij Operatie BRP:
> StatusOverzicht_AdministratieveHandelingen_Berichten.pdf

OK, dan hier de lijst ook nogmaals!
[StatusOverzicht_AdministratieveHandelingen_Berichten.pdf](https://github.com/VNG-Realisatie/Squad-Architectuur-Samen-Organiseren/files/2763167/StatusOverzicht_AdministratieveHandelingen_Berichten.pdf)

**Comment by TCIMEddy** [comment]
Top we hadden hem nog maar dan is hij voor iedere geïnteresseerde beschikbaar...(dank voor je medewerking)
