### ISSUE TITLE
test MvdP: Goed bezig @eddytimmer Trello geeft toch steeds weer een rustig en vertrouwd beeld ;-)

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#168]

**Comment by jgortmaker1** [comment]
is @eddytimmer nu met @eddytimmer in gesprek?

**Comment by TCIMEddy** [comment]
➤ Jeffrey Gortmaker commented:

hij Synct wel goed...maar is wel heel transparant...
één voordeel: we zijn wel sneller AVG-proof, alles is nu de schuld van @EddyTimmer...dus als hij akkoord is....:-)

**Comment by mrtn78** [comment]
alles syncht idd alle kanten op...
Dit was overigens een test van mij op he ttrello board.... Lijkbaar heeft Eddy zn powerup m gesynched naar Github. De vraag is nu alleen hoe ik dit weer in 2 systemen correct verwijder....

**Comment by TCIMEddy** [comment]
@jgortmaker1 @mrtn78 Dank voor feedback. Denk dat ik toch maar gewoon ga overtypen

**Comment by TCIMEddy** [comment]
➤ Martin van der Plas commented:

Ik zal deze kaart als test ook even verwijderen na een paar minuten (zodat jullie dit iig gelezen hebben .... :-)
