### ISSUE TITLE
Als architect van een gemeente wil ik dat de GEMMA 2 referentiecomponenten aangepast worden aan de huidige ontwikkelingen

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#186]
Als architect van een gemeente wil ik dat de GEMMA 2 referentiecomponenten aangepast worden aan de huidige ontwikkelingen

**Comment by jeffreygortmaker1** [comment]
gaan we voorlopig niet doen.
Architectuur gegevenslandschap/Common Ground ontwikkelen we naast de bestaande GEMMA. "Nieuw naast Oud".
Ik sluit deze.

**Comment by jeffreygortmaker1** [comment]
gaan we voorlopig niet doen.
Architectuur gegevenslandschap/Common Ground ontwikkelen we naast de bestaande GEMMA. "Nieuw naast Oud".
Ik sluit deze.

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als architect van een gemeente wil ik dat de GEMMA 2 referentiecomponenten aangepast worden aan de huidige ontwikkelingen](https://trello.com/c/E56MXxQ5/186-als-architect-van-een-gemeente-wil-ik-dat-de-gemma-2-referentiecomponenten-aangepast-worden-aan-de-huidige-ontwikkelingen)
