### ISSUE TITLE
Als gemeente wil ik weten wat de impact van de verschillende e-depot varianten is op de ZGW standaard en de eisen die aan ZAC worden gesteld 

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#194]

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als gemeente wil ik weten wat de impact van de verschillende e-depot varianten is op de ZGW standaard en de eisen die aan ZAC worden gesteld](https://trello.com/c/KL0MHGqy/202-als-gemeente-wil-ik-weten-wat-de-impact-van-de-verschillende-e-depot-varianten-is-op-de-zgw-standaard-en-de-eisen-die-aan-zac-wo)

**Comment by RitaBerghuis** [comment]
Zodat ik hier rekening mee kan houden bij de aanschaf en inzet van zaakafhandelingssystemen

**Comment by RitaBerghuis** [comment]
Graag ontvang ik bij closen van een issue dat ik heb aangedragen een uitleg waarom dit issue geclosed wordt en/of een verwijzing naar issues waarin de vraag dan wel wordt opgepakt.
