### ISSUE TITLE
Als gemeente wil ik weten wat de impact van common ground is op de mogelijke e-depot varianten en of er wellicht een voorkeursvariant is binnen een horizontale architectuur

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#197]

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als gemeente wil ik weten wat de impact van common ground is op de mogelijke e-depot varianten en of er wellicht een voorkeursvariant is binnen een horizontale architectuur](https://trello.com/c/2E5bYCAy/203-als-gemeente-wil-ik-weten-wat-de-impact-van-common-ground-is-op-de-mogelijke-e-depot-varianten-en-of-er-wellicht-een-voorkeursva)

**Comment by RitaBerghuis** [comment]
Zie ook [Gemma Online - E-Depotvoorzieningen](https://www.gemmaonline.nl/index.php/E-Depotvoorzieningen voor de eDepot-varianten

**Comment by RitaBerghuis** [comment]
Suggestie van onze Informatiebeheer medewerkers om bij het afhandelen van dit issue contact te leggen met LOPAI (Landelijk Overleg van Provinciale archiefinspecteurs).
http://www.provincialearchiefinspecties.nl/

**Comment by RitaBerghuis** [comment]
Graag ontvang ik bij closen van een issue dat ik heb aangedragen een uitleg waarom dit issue geclosed wordt en/of een verwijzing naar issues waarin de vraag dan wel wordt opgepakt.

**Comment by TCIMEddy** [comment]
@RitaBerghuis Issue staat nog steeds op de backlog maar op Trello en ik hou je (persoonlijk) op de hoogte.
