### ISSUE TITLE
Als gemeente wil ik een aantal werkende voorbeelden zien van de nieuwe architectuur (NLX-Proof). (1)

### ISSUE THREAD

**Issue by JWEmmen** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#38]
Als gemeente wil ik een aantal werkende voorbeelden zien van de nieuwe architectuur (NLX-Proof).
Bijvoorbeeld als +1 gemeente i.o.

**Comment by TCIMEddy** [comment]
➤ Eddy Timmer commented:

@jeffreygortmaker1 Prio?

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als gemeente wil ik een aantal werkende voorbeelden zien van de nieuwe architectuur (NLX-Proof). (1)](https://trello.com/c/GhM7QvSp/129-als-gemeente-wil-ik-een-aantal-werkende-voorbeelden-zien-van-de-nieuwe-architectuur-nlx-proof-1)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als gemeente wil ik een aantal werkende voorbeelden zien van de nieuwe architectuur (NLX-Proof). (1)](https://trello.com/c/GhM7QvSp/129-als-gemeente-wil-ik-een-aantal-werkende-voorbeelden-zien-van-de-nieuwe-architectuur-nlx-proof-1)
