### ISSUE TITLE
Als Kerngroep wil ik een aantal eenvoudig werkende voorbeelden laten zien. Bijvoorbeeld op 4 verschillende beleidsterreinen (omgevingswet, burgerzaken, sociaal en openbaargebied). (-2)

### ISSUE THREAD

**Issue by JWEmmen** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#39]
Als Kerngroep wil ik een aantal eenvoudig werkende voorbeelden laten zien. Bijvoorbeeld op 4 verschillende beleidsterreinen (omgevingswet, burgerzaken, sociaal en openbaargebied).

**Comment by TCIMEddy** [comment]
➤ Eddy Timmer commented:

@jeffreygortmaker1 Prio?

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als Kerngroep wil ik een aantal eenvoudig werkende voorbeelden laten zien. Bijvoorbeeld op 4 verschillende beleidsterreinen (omgevingswet, burgerzaken, sociaal en openbaargebied). (-2)](https://trello.com/c/3iPixxZs/128-als-kerngroep-wil-ik-een-aantal-eenvoudig-werkende-voorbeelden-laten-zien-bijvoorbeeld-op-4-verschillende-beleidsterreinen-omgev)
