### ISSUE TITLE
Als ontwikkelaar wil ik weten welke ontwikkeltaal er standaard is om zo beheercomplexiteit te voorkomen. (1)

### ISSUE THREAD

**Issue by MHulst** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#44]
Beschreven welke ontwikkeltalen er worden gebruikt.

**Comment by adgerrits** [comment]
Deze user story kan ook wat algemener van aard worden:

- Het  gaat ook bijv. over 'ontwikkeling' (zeker bij de gewenste 'open ontwikkeling')
- Het gaat meer algemeen over 'tooling'; je kunt er zelfs voor kiezen om ontwikkeltaal als niet-relevant te zien maar bijv. te eisen dat producten via benoemde containertechnologie worden geleverd. Dit lijkt nu bij Common Ground te gebeuren (waar bijv. Go, Python en JavaScript worden gebruikt en op Docker/Kubernetes wordt gestandaardiseerd voor runtime gebruik).

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als ontwikkelaar wil ik weten welke ontwikkeltaal er standaard is om zo beheercomplexiteit te voorkomen. (1)](https://trello.com/c/XKKTqjTF/123-als-ontwikkelaar-wil-ik-weten-welke-ontwikkeltaal-er-standaard-is-om-zo-beheercomplexiteit-te-voorkomen-1)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als ontwikkelaar wil ik weten welke ontwikkeltaal er standaard is om zo beheercomplexiteit te voorkomen. (1)](https://trello.com/c/XKKTqjTF/123-als-ontwikkelaar-wil-ik-weten-welke-ontwikkeltaal-er-standaard-is-om-zo-beheercomplexiteit-te-voorkomen-1)
