### ISSUE TITLE
Als beheerder wil ik een standaard vorm voor de PDC om zo de klanten eenduidig te voorzien van productinformatie. (3)

### ISSUE THREAD

**Issue by MHulst** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#46]
Voor het kunnen leveren van diensten is van belang dat deze diensten functioneel zijn omschreven met de daarbij behorende aansluitvoorwaarden, overeenkomsten en te verwachtte dienstverlening. Deze zaken staan in de PDC (Producten en Dienstencatalogus)

**Definition of ready**

- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en leesbaar)
- [x] Voorzien van Definition of Done 
- [x] Voorzien van taken (naam, uren, smart)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] Users en stakeholder benoemd
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**

- [ ] Portaalt gereed en afgestemd op doelgroep
- [ ] Potentieel publiceerbaar/beschikbaar voor users en stakeholders
- [ ] Peer review heeft plaatsgevonden
- [ ] Demo-gereed (kan getoond worden tijdens demo en is demo materiaal is gereed)
- [ ] ...

**Users**

- Contactpersonen van gemeenten en samenwerkingsverbanden

**Stakeholders**

- gemeenten, samenwerkingsverbanden en beheer

**Acceptatiecriteria**

- duidelijk en leesbaar voor doelgroep (users/stakeholders)
- ..

**Globale oplossingrichting**

In TopDesk (ITSM applicatie) is het mogelijk om een portaal te voorzien van de PDC. Deze diensten kunnen in deze applicatie worden gespecificeerd.

**Taken**

- [ ] Diensten bepalen
- [ ] SLA's bepalen
- [ ] Omschrijvingen maken 
- [ ] Aansluitvoorwaarden indien nodig bepalen
- [ ] ...
- [ ] ...

**Comment by jgortmaker1** [comment]
Akkoord met deze US. NOg niet ready.

@MHulst kun je uitleggen wat je precies bedoelt met diensten en wat de relatie met architectuur SO/CG/GL is en de US verder ready maken (voorzien van taken)??

Wat verwacht je van Arnoud en Jule? Of weten zij dat al?

**Comment by arnoudquanjer** [comment]
nee dat weten ze niet

**Comment by adgerrits** [comment]
Ik neem aan dat het gaat om een serviceregister zoals dat [in de NORA](https://www.noraonline.nl/wiki/Service-register) is gedefinieerd.

**Comment by MHulst** [comment]
@jgortmaker1  die reviewers waren voor de eerste story :)
@adgerrits  Een register gaat over data of informatie als ik het goed begrijp. Waar ik het over heb, gaat niet over data of informatie maar werkelijk over producten en diensten zoals een GT-vast verbinding, GGI netwerk etc. Deze diensten moeten straks door gemeenten afgenomen kunnen worden en de beschrijving van deze diensten staat in een PDC.

**Comment by ehotting** [comment]
Ja! Een Producten en Diensten Catalogus, en vervolgens een heldere beschrijving van de processen, de applicaties die worden gebruikt ter ondersteuning er van, de data... - alles wat VNG R voor gemeenten bedacht heeft ook op VNG R zelf toepassen. :) 

Dan wordt het voor gemeenten helder wat ze van VNG R kunnen verwachten en wat ze moeten doen om gebruik te maken van een dienst.

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als beheerder wil ik een standaard vorm voor de PDC om zo de klanten eenduidig te voorzien van productinformatie. (3)](https://trello.com/c/HSiywlQ5/121-als-beheerder-wil-ik-een-standaard-vorm-voor-de-pdc-om-zo-de-klanten-eenduidig-te-voorzien-van-productinformatie-3)
