### ISSUE TITLE
Als leverancier wil ik weten aan welke eisen mijn producten moeten voldoen zodat ik Common Ground compliant producten kan leveren (5)

### ISSUE THREAD

**Issue by arnoudquanjer** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#48]
**Globale oplossingrichting**

* Welke principes moeten worden gehanteerd
* Welke eisen worden gesteld aan logging en ontsluiting daarvan
* Welke eisen worden gesteld aan de API’s die ik als leverancier lever
* Welke eisen worden gesteld aan de beveiliging van de verbinding van applicaties met NLX
* Welke eisen worden gesteld aan de afhandeling van de authenticatie en autorisatie van eindgebruikers
* Welke eisen worden gesteld aan de afhandeling van de autorisatie van system-to-system koppelingen
* Welke eisen worden gesteld aan de beveiliging van communicatiekanalen

**Comment by TCIMEddy** [comment]
Prima user story en de opdeling in de begeleidende tekst zijn volgens mij user stories die per sprint opgepakt kunnen worden

**Comment by tschijv** [comment]
Samenvoegen met #29

**Comment by WimBakkeren** [comment]
> Prima user story en de opdeling in de begeleidende tekst zijn volgens mij user stories die per sprint opgepakt kunnen worden

**Comment by WimBakkeren** [comment]
Lijkt me te groot voor 1 sprint. Daarnaast overlap met andere userstories zoals #88, #58, #14

**Comment by NCouwenbergh** [comment]
Idee om de oplossingsrichting te gaan slicen? Deze bestaat uit meerdere (reeds bestaande) user stories, zoals bijvoorbeeld de principes en een globale planning voor CG. Vanuit Omgevingswet hebben we ook behoefte aan al deze onderdelen.

**Comment by TCIMEddy** [comment]
@NCouwenbergh @jgortmaker1 Daar ben ik uiteraard altijd een voorstander van :-)

**Comment by TCIMEddy** [comment]
Nog te breed dus iom Jeffrey terug naar de baaklog

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als leverancier wil ik weten aan welke eisen mijn producten moeten voldoen zodat ik Common Ground compliant producten kan leveren (5)](https://trello.com/c/XaX9D9jJ/119-als-leverancier-wil-ik-weten-aan-welke-eisen-mijn-producten-moeten-voldoen-zodat-ik-common-ground-compliant-producten-kan-levere)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als leverancier wil ik weten aan welke eisen mijn producten moeten voldoen zodat ik Common Ground compliant producten kan leveren (5)](https://trello.com/c/XaX9D9jJ/119-als-leverancier-wil-ik-weten-aan-welke-eisen-mijn-producten-moeten-voldoen-zodat-ik-common-ground-compliant-producten-kan-levere)
