### ISSUE TITLE
Als leverancier wil ik weten of NLX een product, of een referentie implementatie op basis van een set specificaties is zodat ik daarmee in mijn productbeleid rekening kan houden

### ISSUE THREAD

**Issue by arnoudquanjer** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#49]
- Als NLX een referentie implementatie is op basis van een set specificaties is dan kan een leverancier zelf een implementatie bouwen en integreren in zijn productsuite 
- Als NLX een product is dan moet de leverancier bepalen hoe NLX samen kan werken met hun producten suite

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als leverancier wil ik weten of NLX een product, of een referentie implementatie op basis van een set specificaties is zodat ik daarmee in mijn productbeleid rekening kan houden](https://trello.com/c/rluyGfuk/118-als-leverancier-wil-ik-weten-of-nlx-een-product-of-een-referentie-implementatie-op-basis-van-een-set-specificaties-is-zodat-ik-d)
