### ISSUE TITLE
Als Kernteam Common Ground wil ik digitale identiteit positioneren in de Enterprise Architectuur om daarmee de uitwisseling tussen een digitale identiteitsoplossing en Common Ground te standaardiseren (1)

### ISSUE THREAD

**Issue by jeffreygortmaker1** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#5]

**Comment by TCIMEddy** [comment]
@jgortmaker1 nog actueel. Zo ja prio en visie

**Comment by adgerrits** [comment]
Gelet op de doelen van CG om dingen echt anders te doen is de column van Bart Jacobs wel een fijne om mee te nemen in de gedachtenvorming: https://ibestuur.nl/weblog/wet-do-achterhaald-en-nodeloos-duur .

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als Kernteam Common Ground wil ik digitale identiteit positioneren in de Enterprise Architectuur om daarmee de uitwisseling tussen een digitale identiteitsoplossing en Common Ground te standaardiseren (1)](https://trello.com/c/LBXYBiFT/162-als-kernteam-common-ground-wil-ik-digitale-identiteit-positioneren-in-de-enterprise-architectuur-om-daarmee-de-uitwisseling-tuss)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als Kernteam Common Ground wil ik digitale identiteit positioneren in de Enterprise Architectuur om daarmee de uitwisseling tussen een digitale identiteitsoplossing en Common Ground te standaardiseren (1)](https://trello.com/c/LBXYBiFT/162-als-kernteam-common-ground-wil-ik-digitale-identiteit-positioneren-in-de-enterprise-architectuur-om-daarmee-de-uitwisseling-tuss)
