### ISSUE TITLE
Als gemeente wil ik NLX kunnen inzetten voor al het berichtenverkeer met keten- en netwerkpartijen zodat ik via één systeem verantwoording kan afleggen over uitwisseling van gegevens (2)

### ISSUE THREAD

**Issue by arnoudquanjer** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#54]
- Bepalen met welke keten- en netwerkpartijen de gemeente nu communiceert
- Bepalen welke uitwisselingsprotocollen gebruikt worden voor uitwisseling
- Bepalen of NLX voor alle uitwisselingen inzetbaar is

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als gemeente wil ik NLX kunnen inzetten voor al het berichtenverkeer met keten- en netwerkpartijen zodat ik via één systeem verantwoording kan afleggen over uitwisseling van gegevens (2)](https://trello.com/c/Zqn9L3gJ/113-als-gemeente-wil-ik-nlx-kunnen-inzetten-voor-al-het-berichtenverkeer-met-keten-en-netwerkpartijen-zodat-ik-via-%C3%A9%C3%A9n-systeem-veran)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als gemeente wil ik NLX kunnen inzetten voor al het berichtenverkeer met keten- en netwerkpartijen zodat ik via één systeem verantwoording kan afleggen over uitwisseling van gegevens (2)](https://trello.com/c/Zqn9L3gJ/113-als-gemeente-wil-ik-nlx-kunnen-inzetten-voor-al-het-berichtenverkeer-met-keten-en-netwerkpartijen-zodat-ik-via-%C3%A9%C3%A9n-systeem-veran)
