### ISSUE TITLE
Als leverancier wil ik weten wat de eisen zijn die aan de logging van applicaties worden gesteld zodat ik er voor kan zorgen dat mijn applicaties daar aan voldoen

### ISSUE THREAD

**Issue by arnoudquanjer** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#58]
**Definition of ready**

- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en leesbaar)
- [x] Voorzien van Definition of Done 
- [x] Voorzien van taken (naam, uren, smart)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] Users en stakeholder benoemd
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**

- [x] Document gereed en afgestemd op doelgroep
- [x] Potentieel publiceerbaar/beschikbaar voor users en stakeholders
- [x] Peer review heeft plaatsgevonden
- [x] Demo-gereed (kan getoond worden tijdens demo en is demo materiaal is gereed)
- [ ] Product owner akkoord

**Users**

- [x] Architecten
- [x] Ontwikkelaars
- [x] product/business managers

**Stakeholders**

- [x] Leveranciers
- [x] Gemeenten
- [x] VNG Realisatie

**Acceptatiecriteria**

- [x] duidelijk en leesbaar voor doelgroep (users/stakeholders)
- [x] er is een beschrijving van de meest voor de hand liggende scenario's voor het vastleggen van verwerkingen en ontsluiting daarvan van met voor- en nadelen van deze scenario's voor de stakeholders
- [x] er is rekening gehouden met het huidig landschap van gemeenten en het toekomstig gegevenslandschap van gemeenten
- [x] er is een beschrijving van de samenhang van de vastlegging van verwerkingen met het register van verwerkingen (#59 & #60)
- [x] er is een afweging gemaakt (en beschreven) tussen de scenario's gebaseerd op de voor- en de nadelen en op basis van deze afweging is een keuze gemaakt voor een oplossingsscenario
- [x] het voorgestelde oplossingsscenario is uitgewerkt tot op een niveau waarmee het ontwikkelteam zelfstandig op basis van het voorgestelde scenario kan starten met de realisatie
- [x] het voorgestelde scenario is gereviewd en is akkoord bevonden
- [x] de voorgestelde scenario voldoet aan vigerende wet- en regelgeving op het gebied van bescherming van de privacy
- [x] het opgeleverde product is demonstrabel (Powerpoint presentatie)

**Taken**

- [x] inventariseren van relevante vigerende wet- en regelgeving
- [x] beschrijven logging scenario's
- [x] in kaart brengen voor en nadelen van beschreven scenario's voor stakeholders
- [x] in kaart brengen logging vereisten
- [x] afwegen voor- en nadelen van scenario's
- [x] opstellen oplossingsscenario

**Comment by WimBakkeren** [comment]
Bedoel je: zodat ik er voor kan zorgen dat mijn applicaties daar aan voldoet en ik dat ook kan testen?

**Comment by arnoudquanjer** [comment]
> Bedoel je: zodat ik er voor kan zorgen dat mijn applicaties daar aan voldoet en ik dat ook kan testen?

Ja, dat wordt bedoeld. Ik pas de omschrijving van de user story aan.

**Comment by jgortmaker1** [comment]
vinkjes gezet: is ready voor sprint1

**Comment by jgortmaker1** [comment]
goed document. met nog wel verbetersuggesties..
gereviewed, zie sharepoint.

**Comment by arnoudquanjer** [comment]
uhmm, de laatste versie staat op Teams....

**Comment by jgortmaker1** [comment]
Waren we al officieel over dan…?
Na vandaag dacht ik…het is in ieder geval nodig…

Groeten,
Jeffrey

Van: Arnoud Quanjer [mailto:notifications@github.com]
Verzonden: dinsdag 23 oktober 2018 07:56
Aan: VNG-Realisatie/cg-architectuur <cg-architectuur@noreply.github.com>
CC: Jeffrey Gortmaker <Jeffrey.Gortmaker@VNG.NL>; Assign <assign@noreply.github.com>
Onderwerp: Re: [VNG-Realisatie/cg-architectuur] Als leverancier wil ik weten wat de eisen zijn die aan de logging van applicaties worden gesteld zodat ik er voor kan zorgen dat mijn applicaties daar aan voldoen (#58)


uhmm, de laatste versie staat op Teams....

**Comment by TCIMEddy** [comment]
Feedback Demo:
- geef samenhang tussen technische en functionele logging
- logging metamodel
- en api
- wat moet ik ermee?
- koppeling naar user story gemeente ik wil als gemeente mijn burgers op de juiste manier informeren hoe zijn gegevens zijn gebruikt (conform AVG etc)

**Comment by TCIMEddy** [comment]
@arnoudquanjer Wil je de verplichte reviewers assingnen
