### ISSUE TITLE
Als stakeholder wil ik weten welke eisen het gegevenslandschap stelt aan een ‘Register van verwerkingen’ zodat ik daar rekening mee kan houden (4)

### ISSUE THREAD

**Issue by arnoudquanjer** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#59]
**Definition of ready**

- [x] Iedereen in het team begrijpt de user story
- [x] Product Owner akkoord
- [x] Voorzien van acceptatiecriteria (duidelijk en leesbaar)
- [x] Voorzien van Definition of Done 
- [x] Voorzien van taken (naam, uren, smart)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] Users en stakeholder benoemd
- [x] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**

- [x] Document gereed en afgestemd op doelgroep
- [x] Potentieel publiceerbaar/beschikbaar voor users en stakeholders
- [x] Peer review heeft plaatsgevonden
- [x] Demo-gereed (kan getoond worden tijdens demo en is demo materiaal is gereed)
- [ ] Product owner akkoord

**Users**

- [x] Architecten
- [x] Ontwikkelaars
- [x] Product/business managers

**Stakeholders**

- [x] Leveranciers
- [x] Gemeenten
- [x] VNG Realisatie

**Acceptatiecriteria**

- [x] er is een beschrijving van de meest voor de hand liggende scenario's voor het vastleggen van de verwerkingensgronden en doelbindingen  
- [x] er is een beschrijving van de samenhang van het register van verwerkingen met de vastlegging van voorkomens van verwerkingen (#58)
- [x] er is een afweging gemaakt (en beschreven) tussen de scenario's gebaseerd op de voor- en de nadelen en op basis van deze afweging is een keuze gemaakt voor een oplossingsscenario
- [x] het voorgestelde oplossingsscenario is uitgewerkt tot op een niveau waarmee het ontwikkelteam zelfstandig op basis van het voorgestelde scenario kan starten met de realisatie
- [x] het voorgestelde scenario is gereviewd en is akkoord bevonden
- [x] de voorgestelde scenario voldoet aan vigerende wet- en regelgeving

**Globale oplossingsrichting**

- Welk informatiemodel wordt voor het register van verwerkingen gehanteerd?
- Welke APIs dienen te worden geboden?
- Wat is de samenhang van het register met de logging van verwerkingen?
- Op welke wijze moet een applicatie gebruik maken van het register van verwerkingen?
- Dient het register historie bij te houden?
- Hoe kan de governance/beheer van het register worden vormgegeven (centraal vs decentraal, uitgifte id’s, foutherstel, ...)
- Op welke manier wordt het register gevuld? Welke functionaliteit dient hiervoor geïmplementeerd te worden?

**Taken**

- [x] Inventariseren en beschrijven inrichtingscenario's
- [x] Beschrijven voor- en nadelen inrichtingscenario's
- [x] Beschrijven doelscenario voor gemeenten
- [x] Beschrijven samenhang van het register van verwerkingen met logregister
- [x] Beschrijven van governance/beheer opties
- [x] Peer review (team)
- [x] Demoversie maken

**Comment by TCIMEddy** [comment]
@jgortmaker1 Jij bent assignees (eigenaar) van de user story totdat deze in een sprint terecht komt

**Comment by jhintzbe** [comment]
Ik ben toch wel benieuwd over welk register van verwerkingen je het hebt? het AVG verplichte register van verwerkingen dat een opsomming is van de gemeentelijke verwerkingen van persoonsgegevens of een logging van het verwerken van persoonsgegevens door processen en systemen?

**Comment by adgerrits** [comment]
Aanvullende vraag: hoe ziet de governance/beheer vh register er uit (centraal vs decentraal, uitgifte id’s, foutherstel, ...)

**Comment by TCIMEddy** [comment]
@jgortmaker1 Ik heb deze user story van de backlog naar ready maken gezet. Wil jij kijken of je akkoord bent en dan uiteraard weer het vinkje zetten. Jouw visie meegeven. Een assignee benoemen en aangeven dat het alleen de bedoeling is dat deze ready wordt gemaakt voor volgende sprint.

**Comment by NCouwenbergh** [comment]
Sluit aan bij #47. Gaat eveneens over eisen die we vanuit CG gaan stellen.

**Comment by arnoudquanjer** [comment]
@jgortmaker1 wat mij betreft ready for sprint

**Comment by TCIMEddy** [comment]
@jgortmaker1 zet je ook nog even wat vinkjes (sorry)

**Comment by TCIMEddy** [comment]
@arnoudquanjer by the way mooi uitgewerkt

**Comment by jgortmaker1** [comment]
ready for sprint
