### ISSUE TITLE
Als leverancier wil ik weten hoe het register van verwerkingen gaat werken zodat ik mijn productbeleid daarmee rekening kan houden (0)

### ISSUE THREAD

**Issue by arnoudquanjer** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#60]
- Lokale of centrale installatie?
- Wie is verantwoordelijk voor de inhoud van het register.
- Is er een vaste set die centraal beheerd en beschikbaar gesteld wordt?
- Kunnen gemeenten eigen verwerkingen toevoegen?
- Welk informatiemodel wordt voor het register van verwerkingen gehanteerd?
- Wat is de samenhang van het register met de logging van verwerkingen
- Op welke wijze moet een applicatie gebruik maken van het register van verwerkingen?
- Dient het register historie bij te houden?

**Comment by arnoudquanjer** [comment]
User story kan vervallen. Samenvoegen met #59

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als leverancier wil ik weten hoe het register van verwerkingen gaat werken zodat ik mijn productbeleid daarmee rekening kan houden (0)](https://trello.com/c/Nto2SuOM/107-als-leverancier-wil-ik-weten-hoe-het-register-van-verwerkingen-gaat-werken-zodat-ik-mijn-productbeleid-daarmee-rekening-kan-houd)
