### ISSUE TITLE
Als gemeente wil ik weten hoe ik Common Ground in mijn aanbestedingen van komende 2 jaar kan meenemen, zodat ik nu al de juiste stappen zet op weg naar het Common Ground gedachte goed. (3)

### ISSUE THREAD

**Issue by NCouwenbergh** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#70]
De Omgevingswet vraagt om aanpassingen aan de gemeentelijke software. Hiervoor stellen we requirements op. In deze requirements nemen we direct ook de eisen aan Common Ground op. Voor het beantwoorden van deze vraag zijn producten nodig vanuit Common Ground. Denk hierbij aan visie, principes, groeipad etc. Deze zijn echter nog niet beschikbaar.

Om toch met requirements te kunnen starten, baseren we de deze op dat wat nu al bekend is over Common Ground. Op het moment dat in volgende sprints meer Common Ground producten beschikbaar komen, kunnen deze op de requirements toegepast worden. Zo werken we iteratief aan de requirements.

**Comment by TCIMEddy** [comment]
@jgortmaker1 Ik heb deze user story van de backlog naar ready maken gezet. Wil jij kijken of je akkoord bent en dan uiteraard weer het vinkje zetten. Jouw visie meegeven. Een assignee benoemen en aangeven dat het alleen de bedoeling is dat deze ready wordt gemaakt voor volgende sprint.

**Comment by jgortmaker1** [comment]
wel belangrijk, maar hoeft niet m.i. niet in sprint 2. terug naar BL

**Comment by NCouwenbergh** [comment]
**Definition of ready**
[ ] Iedereen in het team begrijpt de user story
[ ] Is klein genoeg (maximaal 1/5 van sprint)
[ ] Product Owner akkoord
[ ] Voorzien van acceptatiecriteria (duidelijk en leesbaar)
[ ] Voorzien van Definition of Done
[ ] Voorzien van taken (naam, uren, smart)
[ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
[ ] Users en stakeholder benoemd
[ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
[ ] Document gereed en afgestemd op doelgroep
[ ] Potentieel publiceerbaar/beschikbaar voor users en stakeholders
[ ] Peer review heeft plaatsgevonden
[ ] Demo-gereed (kan getoond worden tijdens demo en is demo materiaal is gereed)

**Users**
- Architecten Omgevingswet

**Stakeholders**
- VNG realisatie
- VNG Realisatie Architecten
- Gemeenten

**Acceptatiecriteria**
- duidelijk en leesbaar voor doelgroep (users/stakeholders)
- Via GEMMA online ontsloten
- Globale oplossingsrichting

De Omgevingswet vraagt om aanpassingen aan de gemeentelijke software. Hiervoor stellen we requirements op. In deze requirements nemen we direct ook de eisen aan Common Ground op. Voor het beantwoorden van deze vraag zijn producten nodig vanuit Common Ground. Denk hierbij aan visie, principes, groeipad etc. Deze zijn echter nog niet beschikbaar.

Om toch met requirements te kunnen starten, baseren we de deze op dat wat nu al bekend is over Common Ground. Op het moment dat in volgende sprints meer Common Ground producten beschikbaar komen, kunnen deze op de requirements toegepast worden. Zo werken we iteratief aan de requirements.

**Taken**
- verwerken 5 lagen model in requirements (Nils)
- verwerken van scheiding van proces en data in requirements (Nils)
- updaten van teksten mbt common ground (Nils)

**Comment by TCIMEddy** [comment]
@jgortmaker1 Deze staat in ready for sprint. Is dit correct en blijft deze hier staan voor sprint 4.

**Comment by TCIMEddy** [comment]
Graag ready for sprint voor 31 januari 2018

**Comment by TCIMEddy** [comment]
➤ Eddy Timmer commented:

@jeffreygortmaker1 zitten 2 prio's aan!

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als gemeente wil ik weten hoe ik Common Ground in mijn aanbestedingen van komende 2 jaar kan meenemen, zodat ik nu al de juiste stappen zet op weg naar het Common Ground gedachte goed. (3)](https://trello.com/c/8PALn00T/97-als-gemeente-wil-ik-weten-hoe-ik-common-ground-in-mijn-aanbestedingen-van-komende-2-jaar-kan-meenemen-zodat-ik-nu-al-de-juiste-s)
