### ISSUE TITLE
Als architect van Ketenbureau i-Sociaal domein (voorheen ISD-Regie) wil ik weten wat Common Ground betekent voor de de ISD-keten (welke eisen het stelt, welke impact het er op heeft, hoe de keten past in Common Ground) zodat we bij het Ketenbureau de ontwi

### ISSUE THREAD

**Issue by WimBakkeren** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#76]
Globale oplossingrichting
Een beknopt overzicht, gebaseerd op (door Common Ground beïnvloede) instrumenten en het werkingsgebied van het Ketenbureau i-Sociaal domein waarbij de impact van Common Ground wordt beschreven.

**Comment by TCIMEddy** [comment]
➤ Eddy Timmer commented:

@jeffreygortmaker1 Wil jij prio toevoegen (stond op Prio ?)

**Comment by WimBakkeren** [comment]
@jgortmaker1 @TCIMEddy  Ik ben geen architect ISD meer. Dat is @RdeZ nu. Hij kan de prioriteit bepalen.
@TCIMEddy het is @jgortmaker1 ipv @jeffreygortmaker1

**Comment by TCIMEddy** [comment]
@WimBakkeren Dank voor je opmerkzaamheid. De oorzaak is de conversie naar Trello. 2 verschillende email. Hoop dat dit goed gaat.

**Comment by jeffreygortmaker1** [comment]
ik heb mijn github username aangepast :-)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als architect van Ketenbureau i-Sociaal domein (voorheen ISD-Regie) wil ik weten wat Common Ground betekent voor de de ISD-keten (welke eisen het stelt, welke impact het er op heeft, hoe de keten past in Common Ground) zodat we bij het Ketenbureau de ontwi](https://trello.com/c/1hzpxfcO/91-als-architect-van-ketenbureau-i-sociaal-domein-voorheen-isd-regie-wil-ik-weten-wat-common-ground-betekent-voor-de-de-isd-keten-w)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als architect van Ketenbureau i-Sociaal domein (voorheen ISD-Regie) wil ik weten wat Common Ground betekent voor de de ISD-keten (welke eisen het stelt, welke impact het er op heeft, hoe de keten past in Common Ground) zodat we bij het Ketenbureau de ontwi](https://trello.com/c/1hzpxfcO/91-als-architect-van-ketenbureau-i-sociaal-domein-voorheen-isd-regie-wil-ik-weten-wat-common-ground-betekent-voor-de-de-isd-keten-w)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als architect van Ketenbureau i-Sociaal domein (voorheen ISD-Regie) wil ik weten wat Common Ground betekent voor de de ISD-keten (welke eisen het stelt, welke impact het er op heeft, hoe de keten past in Common Ground) zodat we bij het Ketenbureau de ontwi](https://trello.com/c/1hzpxfcO/91-als-architect-van-ketenbureau-i-sociaal-domein-voorheen-isd-regie-wil-ik-weten-wat-common-ground-betekent-voor-de-de-isd-keten-w)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als architect van Ketenbureau i-Sociaal domein (voorheen ISD-Regie) wil ik weten wat Common Ground betekent voor de de ISD-keten (welke eisen het stelt, welke impact het er op heeft, hoe de keten past in Common Ground) zodat we bij het Ketenbureau de ontwi](https://trello.com/c/1hzpxfcO/91-als-architect-van-ketenbureau-i-sociaal-domein-voorheen-isd-regie-wil-ik-weten-wat-common-ground-betekent-voor-de-de-isd-keten-w)
