### ISSUE TITLE
Als adviseur bij DSO-CG wil ik weten welke producten nodig zijn en hoe we die producten maken om Common Ground te implementeren in een situatie waar de software die gemeenten gebruiken wordt geleverd door leveranciers van (standaard) software zodat duideli

### ISSUE THREAD

**Issue by WimBakkeren** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#78]

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als adviseur bij DSO-CG wil ik weten welke producten nodig zijn en hoe we die producten maken om Common Ground te implementeren in een situatie waar de software die gemeenten gebruiken wordt geleverd door leveranciers van (standaard) software zodat duideli](https://trello.com/c/M8d0bFwy/89-als-adviseur-bij-dso-cg-wil-ik-weten-welke-producten-nodig-zijn-en-hoe-we-die-producten-maken-om-common-ground-te-implementeren)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als adviseur bij DSO-CG wil ik weten welke producten nodig zijn en hoe we die producten maken om Common Ground te implementeren in een situatie waar de software die gemeenten gebruiken wordt geleverd door leveranciers van (standaard) software zodat duideli](https://trello.com/c/M8d0bFwy/89-als-adviseur-bij-dso-cg-wil-ik-weten-welke-producten-nodig-zijn-en-hoe-we-die-producten-maken-om-common-ground-te-implementeren)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als adviseur bij DSO-CG wil ik weten welke producten nodig zijn en hoe we die producten maken om Common Ground te implementeren in een situatie waar de software die gemeenten gebruiken wordt geleverd door leveranciers van (standaard) software zodat duideli](https://trello.com/c/M8d0bFwy/89-als-adviseur-bij-dso-cg-wil-ik-weten-welke-producten-nodig-zijn-en-hoe-we-die-producten-maken-om-common-ground-te-implementeren)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als adviseur bij DSO-CG wil ik weten welke producten nodig zijn en hoe we die producten maken om Common Ground te implementeren in een situatie waar de software die gemeenten gebruiken wordt geleverd door leveranciers van (standaard) software zodat duideli](https://trello.com/c/M8d0bFwy/89-als-adviseur-bij-dso-cg-wil-ik-weten-welke-producten-nodig-zijn-en-hoe-we-die-producten-maken-om-common-ground-te-implementeren)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als adviseur bij DSO-CG wil ik weten welke producten nodig zijn en hoe we die producten maken om Common Ground te implementeren in een situatie waar de software die gemeenten gebruiken wordt geleverd door leveranciers van (standaard) software zodat duideli](https://trello.com/c/M8d0bFwy/89-als-adviseur-bij-dso-cg-wil-ik-weten-welke-producten-nodig-zijn-en-hoe-we-die-producten-maken-om-common-ground-te-implementeren)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als adviseur bij DSO-CG wil ik weten welke producten nodig zijn en hoe we die producten maken om Common Ground te implementeren in een situatie waar de software die gemeenten gebruiken wordt geleverd door leveranciers van (standaard) software zodat duideli](https://trello.com/c/M8d0bFwy/89-als-adviseur-bij-dso-cg-wil-ik-weten-welke-producten-nodig-zijn-en-hoe-we-die-producten-maken-om-common-ground-te-implementeren)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als adviseur bij DSO-CG wil ik weten welke producten nodig zijn en hoe we die producten maken om Common Ground te implementeren in een situatie waar de software die gemeenten gebruiken wordt geleverd door leveranciers van (standaard) software zodat duideli](https://trello.com/c/M8d0bFwy/89-als-adviseur-bij-dso-cg-wil-ik-weten-welke-producten-nodig-zijn-en-hoe-we-die-producten-maken-om-common-ground-te-implementeren)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als adviseur bij DSO-CG wil ik weten welke producten nodig zijn en hoe we die producten maken om Common Ground te implementeren in een situatie waar de software die gemeenten gebruiken wordt geleverd door leveranciers van (standaard) software zodat duideli](https://trello.com/c/M8d0bFwy/89-als-adviseur-bij-dso-cg-wil-ik-weten-welke-producten-nodig-zijn-en-hoe-we-die-producten-maken-om-common-ground-te-implementeren)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als adviseur bij DSO-CG wil ik weten welke producten nodig zijn en hoe we die producten maken om Common Ground te implementeren in een situatie waar de software die gemeenten gebruiken wordt geleverd door leveranciers van (standaard) software zodat duideli](https://trello.com/c/M8d0bFwy/89-als-adviseur-bij-dso-cg-wil-ik-weten-welke-producten-nodig-zijn-en-hoe-we-die-producten-maken-om-common-ground-te-implementeren)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als adviseur bij DSO-CG wil ik weten welke producten nodig zijn en hoe we die producten maken om Common Ground te implementeren in een situatie waar de software die gemeenten gebruiken wordt geleverd door leveranciers van (standaard) software zodat duideli](https://trello.com/c/M8d0bFwy/89-als-adviseur-bij-dso-cg-wil-ik-weten-welke-producten-nodig-zijn-en-hoe-we-die-producten-maken-om-common-ground-te-implementeren)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als adviseur bij DSO-CG wil ik weten welke producten nodig zijn en hoe we die producten maken om Common Ground te implementeren in een situatie waar de software die gemeenten gebruiken wordt geleverd door leveranciers van (standaard) software zodat duideli](https://trello.com/c/M8d0bFwy/89-als-adviseur-bij-dso-cg-wil-ik-weten-welke-producten-nodig-zijn-en-hoe-we-die-producten-maken-om-common-ground-te-implementeren)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als adviseur bij DSO-CG wil ik weten welke producten nodig zijn en hoe we die producten maken om Common Ground te implementeren in een situatie waar de software die gemeenten gebruiken wordt geleverd door leveranciers van (standaard) software zodat duideli](https://trello.com/c/M8d0bFwy/89-als-adviseur-bij-dso-cg-wil-ik-weten-welke-producten-nodig-zijn-en-hoe-we-die-producten-maken-om-common-ground-te-implementeren)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als adviseur bij DSO-CG wil ik weten welke producten nodig zijn en hoe we die producten maken om Common Ground te implementeren in een situatie waar de software die gemeenten gebruiken wordt geleverd door leveranciers van (standaard) software zodat duideli](https://trello.com/c/M8d0bFwy/89-als-adviseur-bij-dso-cg-wil-ik-weten-welke-producten-nodig-zijn-en-hoe-we-die-producten-maken-om-common-ground-te-implementeren)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als adviseur bij DSO-CG wil ik weten welke producten nodig zijn en hoe we die producten maken om Common Ground te implementeren in een situatie waar de software die gemeenten gebruiken wordt geleverd door leveranciers van (standaard) software zodat duideli](https://trello.com/c/M8d0bFwy/89-als-adviseur-bij-dso-cg-wil-ik-weten-welke-producten-nodig-zijn-en-hoe-we-die-producten-maken-om-common-ground-te-implementeren)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als adviseur bij DSO-CG wil ik weten welke producten nodig zijn en hoe we die producten maken om Common Ground te implementeren in een situatie waar de software die gemeenten gebruiken wordt geleverd door leveranciers van (standaard) software zodat duideli](https://trello.com/c/M8d0bFwy/89-als-adviseur-bij-dso-cg-wil-ik-weten-welke-producten-nodig-zijn-en-hoe-we-die-producten-maken-om-common-ground-te-implementeren)
