### ISSUE TITLE
Als gemeente wil ik dat de opgeleverde architectuur mij inzicht geeft in een migratiestrategie en aanpak omdat ik de andere CG resultaten wel enige tijd gezamelijk naast elkaar moet kunnen gebruiken zonder in een instabiele situatie te komen voor mijn bedr

### ISSUE THREAD

**Issue by jhintzbe** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#83]

**Comment by hdksi** [comment]
#15

**Comment by adgerrits** [comment]
Tip: in de position-paper sourcing lees ik dat er gedacht wordt in termijnen van 5 tot 10 jaar. Bij uitgangspunten voor aanpak (van oa Common Ground) lees ik dat er vraaggestuurd en kort iteratief ontwikkeld gaat worden. Het  is wel een uitdaging om die samen te brengen en te komen tot een heldere migratiestrategie (en verder te komen dan een strategie als 'we werken agile en stellen bij als dat nodig is').

**Comment by TCIMEddy** [comment]
➤ Eddy Timmer commented:

@jeffreygortmaker1 Prio!

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als gemeente wil ik dat de opgeleverde architectuur mij inzicht geeft in een migratiestrategie en aanpak omdat ik de andere CG resultaten wel enige tijd gezamelijk naast elkaar moet kunnen gebruiken zonder in een instabiele situatie te komen voor mijn bedr](https://trello.com/c/0jDvIQ6X/84-als-gemeente-wil-ik-dat-de-opgeleverde-architectuur-mij-inzicht-geeft-in-een-migratiestrategie-en-aanpak-omdat-ik-de-andere-cg-r)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als gemeente wil ik dat de opgeleverde architectuur mij inzicht geeft in een migratiestrategie en aanpak omdat ik de andere CG resultaten wel enige tijd gezamelijk naast elkaar moet kunnen gebruiken zonder in een instabiele situatie te komen voor mijn bedr](https://trello.com/c/0jDvIQ6X/84-als-gemeente-wil-ik-dat-de-opgeleverde-architectuur-mij-inzicht-geeft-in-een-migratiestrategie-en-aanpak-omdat-ik-de-andere-cg-r)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als gemeente wil ik dat de opgeleverde architectuur mij inzicht geeft in een migratiestrategie en aanpak omdat ik de andere CG resultaten wel enige tijd gezamelijk naast elkaar moet kunnen gebruiken zonder in een instabiele situatie te komen voor mijn bedr](https://trello.com/c/0jDvIQ6X/84-als-gemeente-wil-ik-dat-de-opgeleverde-architectuur-mij-inzicht-geeft-in-een-migratiestrategie-en-aanpak-omdat-ik-de-andere-cg-r)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als gemeente wil ik dat de opgeleverde architectuur mij inzicht geeft in een migratiestrategie en aanpak omdat ik de andere CG resultaten wel enige tijd gezamelijk naast elkaar moet kunnen gebruiken zonder in een instabiele situatie te komen voor mijn bedr](https://trello.com/c/0jDvIQ6X/84-als-gemeente-wil-ik-dat-de-opgeleverde-architectuur-mij-inzicht-geeft-in-een-migratiestrategie-en-aanpak-omdat-ik-de-andere-cg-r)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als gemeente wil ik dat de opgeleverde architectuur mij inzicht geeft in een migratiestrategie en aanpak omdat ik de andere CG resultaten wel enige tijd gezamelijk naast elkaar moet kunnen gebruiken zonder in een instabiele situatie te komen voor mijn bedr](https://trello.com/c/0jDvIQ6X/84-als-gemeente-wil-ik-dat-de-opgeleverde-architectuur-mij-inzicht-geeft-in-een-migratiestrategie-en-aanpak-omdat-ik-de-andere-cg-r)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als gemeente wil ik dat de opgeleverde architectuur mij inzicht geeft in een migratiestrategie en aanpak omdat ik de andere CG resultaten wel enige tijd gezamelijk naast elkaar moet kunnen gebruiken zonder in een instabiele situatie te komen voor mijn bedr](https://trello.com/c/0jDvIQ6X/84-als-gemeente-wil-ik-dat-de-opgeleverde-architectuur-mij-inzicht-geeft-in-een-migratiestrategie-en-aanpak-omdat-ik-de-andere-cg-r)

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als gemeente wil ik dat de opgeleverde architectuur mij inzicht geeft in een migratiestrategie en aanpak omdat ik de andere CG resultaten wel enige tijd gezamelijk naast elkaar moet kunnen gebruiken zonder in een instabiele situatie te komen voor mijn bedr](https://trello.com/c/0jDvIQ6X/84-als-gemeente-wil-ik-dat-de-opgeleverde-architectuur-mij-inzicht-geeft-in-een-migratiestrategie-en-aanpak-omdat-ik-de-andere-cg-r)
