### ISSUE TITLE
Als architect/ontwikkelaar van een gemeentelijke leverancier wil ik gebruik maken van een gestandaardiseerd VTH-informatiemodel. (1)

### ISSUE THREAD

**Issue by tschijv** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#89]
zodat ik beter kan aansluiten via de gestandaardiseerde services op andere toepassingen

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als architect/ontwikkelaar van een gemeentelijke leverancier wil ik gebruik maken van een gestandaardiseerd VTH-informatiemodel. (1)](https://trello.com/c/cHLEjcjF/78-als-architect-ontwikkelaar-van-een-gemeentelijke-leverancier-wil-ik-gebruik-maken-van-een-gestandaardiseerd-vth-informatiemodel)
