### ISSUE TITLE
Als architect bij VNGR-projecten wil ik weten hoe de implementatie (deployment) van Common Ground eruit ziet zodat ik daar in mijn projecten rekening mee kan houden. (3)

### ISSUE THREAD

**Issue by WimBakkeren** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#90]
Komen er centrale componenten? Welke?
Ontwikkelt VNGR / Common Ground zelf componenten?
Hoe benader ik de gegevens(services) van een andere organisatie? Direct of via een knooppunt / gateway oid?
Komt er een centrale infrastructuur?

**Comment by TCIMEddy** [comment]
> Komen er centrale componenten? Welke?
> Ontwikkelt VNGR / Common Ground zelf componenten?
> Hoe benader ik de gegevens(services) van een andere organisatie? Direct of via een knooppunt / gateway oid?
> Komt er een centrale infrastructuur?

**Comment by TCIMEddy** [comment]
@jgortmaker1 Ik heb deze user story van de backlog naar ready maken gezet. Wil jij kijken of je akkoord bent en dan uiteraard weer het vinkje zetten. Jouw visie meegeven. Een assignee benoemen en aangeven dat het alleen de bedoeling is dat deze ready wordt gemaakt voor volgende sprint.

**Comment by jgortmaker1** [comment]
@tschijv en @WimBakkeren zoals afgesproken deze USs even op jullie naam gezet. Kijken jullie even welke jullie in Sprint 2 willen (omgevingswet) oppakken?

een andere mag evt ook.
US die we niet oppakken mogen terug naar de Backlog..

**Comment by WimBakkeren** [comment]
Deze moeten we slicen. Het is te groot voor 1 sprint. Daar heb ik meer tijd voor nodig en ook iemand om mee te sparren. Ook is er samenhang met US #77 

Ik stel voor dat @tschijv en ik een poging doen op korte termijn.

**Comment by WimBakkeren** [comment]
Deze ook aankomende dinsdag @tschijv ?

**Comment by tschijv** [comment]
Prima!

**Comment by TCIMEddy** [comment]
@jgortmaker1 deze staat in de ready maken kolom zonder prio. Graag prio en eventueel visie

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als architect bij VNGR-projecten wil ik weten hoe de implementatie (deployment) van Common Ground eruit ziet zodat ik daar in mijn projecten rekening mee kan houden. (3)](https://trello.com/c/k4h8oy93/77-als-architect-bij-vngr-projecten-wil-ik-weten-hoe-de-implementatie-deployment-van-common-ground-eruit-ziet-zodat-ik-daar-in-mijn)
