### ISSUE TITLE
Als scrumteam willen we genoeg en duidelijk communiceren zodat er draagvlak ontstaat voor de opgeleverd procucten

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#94]
WIP @hdksi Ik voeg lijstje nog toe maar ga je gang met ideeën hieromtrent

**Comment by hdksi** [comment]
@TCIMEddy levert deze story een product op? Of is dit een continue aanbeveling :)

**Comment by hdksi** [comment]
Ja daarom probeer ik met stories zoals #142 meer concrete doelen te stellen. Ik heb de DoD en taken aangepast, maar het komt neer op gedisciplineerd publiceren en daarover communiceren denk ik. Ik neem graag de taak op me om dat te bewaken. Maar het blijft meer een procesdingetje dan een taak met een kop en een staart denk ik.

**Comment by hdksi** [comment]
We hebben duidelijk wat issues met publiceren (er staan pas 3 documenten op GO) en de map 'klaar voor publicatie' is Teams is leeg. Echter, voor wat betreft deze story: het is me niet duidelijk wanneer die 'done' is. Kunnnen we hem meer richten op publicatie in plaats van communicatie in het algemeen?

**Comment by TCIMEddy** [comment]
@hdksi Moet communicatie nog worden aangehaakt of kunnen we deze user story als done beschouwen?
