### ISSUE TITLE
Als gegevensarchitect in een project wil ik weten welke afspraken er van toepassing zijn voor het vastleggen van gegevensspecificaties in het Sociaal Domein

### ISSUE THREAD

**Issue by jeffreygortmaker1** [VNG-Realisatie/Squad-Architectuur-Samen-Organiseren#96]
...zodat ik weet aan welke eisen een op te leveren informatiemodel binnen dat domein moet voldoen.

**Comment by WimBakkeren** [comment]
Dit lijkt me te veel voor 1 sprint. Er zijn vele richtlijnen te geven voor het maken van informatiemodellen, variërend van welke modelleertechnieken je hanteert tot de naamgeving van entiteiten en attributen. Naar welk soort richtlijnen ben je op zoek?

**Comment by Debatse** [comment]
> Dit lijkt me te veel voor 1 sprint. Er zijn vele richtlijnen te geven voor het maken van informatiemodellen, variërend van welke modelleertechnieken je hanteert tot de naamgeving van entiteiten en attributen. Naar welk soort richtlijnen ben je op zoek?

**Comment by Debatse** [comment]
Sorry er ging iets mis. Maar afgelopen jaren hebben we hiervoor al heel veel werk verricht. Er is een metamodel voor informatiemodellen waarin afgesproken is in welke modelleertaal het informatiemodel moet worden vastgelegd, uit welke bouwstenen dat model bestaat e.d.. Dit model is samen met Kadaster en Geonovum opgesteld. Voor gemeenten hebben we als VNG realisatie een aanvullende eisen gespecificeerd (MIG). Het RSGB, RGBZ en imZTC zijn gebaseerd op dit metamodel. Bedoeling is dat als er informatiemodellen voor een domein binnen de gemeente worden opgesteld deze ook op die manier worden gespecificeerd.

**Comment by TCIMEddy** [comment]
Lijkt me prima user story, ik kan niet beoordelen of dit in 1 sprint kan. @jgortmaker1 vinkje zetten bij PO

**Comment by jgortmaker1** [comment]
nu hebben we een dubbel.. wschl mijn schuld :-(
eentje was bedoeld om samen met Ronald naar modelleerafspraken en het sociaal domein te kijken (voorstel deze: #96)
De andere meer in het algemeen (dat is dan #85 )

@Debatse: kun je deze US wat specifieker maken voor het sociaal domein en kijken of er hier nog iets staat wat we in #85 gemist hebben? dan is het duidelijk en vergis ik me niet meer..

**Comment by Debatse** [comment]
Is mijn schul. Tooling is niet je van het. even wennen. Maar zal deze (nr96) nog wel aanpassen

**Comment by TCIMEddy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als gegevensarchitect in een project wil ik weten welke afspraken er van toepassing zijn voor het vastleggen van gegevensspecificaties in het Sociaal Domein](https://trello.com/c/92XWGukY/71-als-gegevensarchitect-in-een-project-wil-ik-weten-welke-afspraken-er-van-toepassing-zijn-voor-het-vastleggen-van-gegevensspecifi)
